services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: mgadmin
      POSTGRES_PASSWORD: 123
      POSTGRES_ROOT_PASSWORD: 123
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U mgadmin"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - article-network
  frontend:
    container_name: amt_frontend
    build:
      context: article_frontend/.
      dockerfile: Dockerfile
    image: article_frontend:latest
    ports:
    - 80:80
    depends_on:
      - backend
    networks:
      - article-network
  backend:
    container_name: amt-api
    build:
      context: article_api/.
      dockerfile: Dockerfile
    image: article_api:latest
    ports:
    - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - article-network
networks:
  article-network: